
[tool.pyflow]
name = ""
py_version = "3.9"
version = "0.1.0"

[tool.pyflow.scripts]

[tool.pyflow.dependencies]
selenium = "^2.33.0"
python-dotenv = "^0.19.2"
python-dateutil = "^2.8.2"
charset-normalizer = "^2.0.12"
requests = "^2.27.1"

[tool.pyflow.dev-dependencies]

